require('flot/source/jquery.colorhelpers.js')
require('flot/source/jquery.canvaswrapper.js')
require('flot/source/jquery.flot.js')
require('flot/source/jquery.flot.saturated.js')
require('flot/source/jquery.flot.browser.js')
require('flot/source/jquery.flot.drawSeries.js')
require('flot/source/jquery.flot.uiConstants.js')
require('flot/source/jquery.flot.logaxis.js')
require('flot/source/jquery.flot.symbol.js')
require('flot/source/jquery.flot.flatdata.js')
require('flot/source/jquery.flot.navigate.js')
require('flot/source/jquery.flot.touchNavigate.js')
require('flot/source/jquery.flot.hover.js')
require('flot/source/jquery.flot.touch.js')
require('flot/source/jquery.flot.time.js')
require('flot/source/jquery.flot.axislabels.js')
require('flot/source/jquery.flot.selection.js')
require('flot/source/jquery.flot.composeImages.js')
require('flot/source/jquery.flot.legend.js')
require('flot/source/jquery.flot.pie.js');
require('flot/source/jquery.flot.categories.js');
require('flot/source/jquery.flot.resize.js');
require('./tooltip.js');
