require('core-js/features/promise')
require('core-js/features/array')
require('core-js/features/string')
require('core-js/features/object')
require('core-js/features/weak-map')
require('core-js/features/symbol')
